<?php
try {
    // Reading from STDIN
    $data = trim(fgets(STDIN));
    if (empty($data)) {
        throw new Exception('Please provide valid data to be checked');
    }

    // Converting JSON
    $data = json_decode($data);
    if ((empty($data)) || (empty($data->message)) || (empty($data->auth))) {
        throw new Exception('This script only accepts data generated by 03-auth.php');
    }
    if (($data->auth = sodium_hex2bin($data->auth)) === false) {
        throw new Exception('Bad format provided. Please run 03-auth.php first.');
    }

    // Reading key
    $key = trim(file_get_contents('03-auth.key'));

    // Verifica a assinatura
    if (!sodium_crypto_auth_verify($data->auth, $data->message, $key)) {
        sodium_memzero($key);
        throw new Exception('Authentication failed');
    }

    sodium_memzero($key);
    echo "\e[0;32mSuccessfully authenticated\e[0m" . PHP_EOL;
} catch (Exception $e) {
    echo "\e[0;31m{$e->getMessage()}\e[0m" . PHP_EOL;
    die(1);
}
